### ISSUE TITLE
mistserver on archlinux arm

### ISSUE THREAD

**Issue by qinohe** [DDVTECH/mistserver#12]
Hi thanks for your software in the first place.
I have build the server on archlinux arm (armv7h RaspberryPi2) , with a home brew PKGBUILD

It gives me a warning about a unsigned intger in timings.cpp

`src/mistserver-git/lib/timing.cpp:68:3: warning: this decimal constant is unsigned only in ISO C90
   return ((((long long int)t.tv_sec) + 2208988800) << 32) + (t.tv_nsec * 4.2949);`

I patched with --- See next post
`diff -aur mistserver-git.a/lib/timing.cpp mistserver-git.b/lib/timing.cpp`
`--- mistserver-git.a/lib/timing.cpp    2016-01-29 16:33:35.306150858 +0100`
`+++ mistserver-git.b/lib/timing.cpp    2016-01-29 16:35:49.725261635 +0100`
`@@ -65,7 +65,7 @@`
`long long Util::getNTP() {`
`struct timespec t;`
`clock_gettime(CLOCK_REALTIME, &t);`
`-  return ((((long long int)t.tv_sec) + 2208988800) << 32) + (t.tv_nsec * 4.2949);`
`+  return ((((long long int)t.tv_sec) + 2208988800U) << 32) + (t.tv_nsec * 4.2949);`
 `}`

 `/// Gets the current time in millisecon`

Now it builds without issues. Thought you would like to know , thanks qinohe

**Comment by qinohe** [comment]
Dove a little bit deeper into the number '2208988800', and what it represents, and it's about the epoch on a 32 bit system. This machine is a RaspberryPi 2, and it honers the 32bit epoch fail after 2147483647 which will be 'Tue Jan 19 04:14:07 CET 2038' (local Netherlands). 2147483648 will fail.The next patch builds without problems, and is better than the former.

`diff -aur mistserver-git.a/lib/timing.cpp mistserver-git.b/lib/timing.cpp`
`--- mistserver-git.a/lib/timing.cpp	2016-01-29 19:20:44.204785618 +0100`
`+++ mistserver-git.b/lib/timing.cpp	2016-01-29 19:24:30.763429287 +0100`
`@@ -65,7 +65,7 @@`
` long long Util::getNTP() {`
`   struct timespec t;`
`   clock_gettime(CLOCK_REALTIME, &t);`
`-  return ((((long long int)t.tv_sec) + 2208988800) << 32) + (t.tv_nsec * 4.2949);`
`+  return ((((long long int)t.tv_sec) + 2147483647) << 32) + (t.tv_nsec * 4.2949);`
` }`
 
` /// Gets the current time in milliseconds.`

**Comment by Thulinma** [comment]
Thanks! We're actually working on a long overdue change to the source that will make it fully compatible with other processor types, and will make sure to pick this up during that!

**Comment by gdm85** [comment]
By the way, for those willing to try a binary ARMHF build I have put mine on:
https://dl.bintray.com/gdm85/ubuntu14-bin/

(latest master) It was not possible to build with `make -j` because of memory limitations of my device, but in the end it finished successfully (albeit the warnings). Now I am going to give this a try :)

**Comment by Thulinma** [comment]
ARMv7 and ARMv8-64 builds are now officially supported (and available on the website).
Should there still be any problems with compiling on ARM, feel free to re-open this issue.
