### ISSUE TITLE
Provide a REST WS for grabbing statistics

### ISSUE THREAD

**Issue by edwardoliveira** [DDVTECH/mistserver#13]
The '/api@Statistics' is pretty cool, but it would be nice if we had more freedom to get MistServer statistics as a JSON/XML so that we could plug it on our custom monitoring software.

Maybe https://github.com/DDVTECH/mistserver/blob/d8f57afae1b197a894d4cc1299c132d0e53a9946/api/mist_api.sh is a start?

**Comment by Thulinma** [comment]
Starting with the 2.6 release, MistServer Pro actually contains full instrumentation support through the --prometheus command line option. This will expose a REST endpoint in both prometheus format and in plain JSON with much more statistics than just what the API provides. This is an extremely powerful feature and will allow you to use practically any monitoring software you may want to.

In the open source edition of course it's possible to retrieve the source data used for the statistics page in the interface. The documentation for this can be found here: http://mistserver.org/doxygen/api.html
(and indeed this is what the mist_api.sh file exposes over a command line interface)
