### ISSUE TITLE
continuity_counter is reset on HLS segment split

### ISSUE THREAD

**Issue by premultiply** [DDVTECH/mistserver#14]
I noticed that in HLS output there are CC errors for video and audio PIDs between TS-segment boundaries.
So it looks like CC counters are reset on segment split by mistake.

[https://trac.ffmpeg.org/ticket/2828]

System: MistServer Pro 2.7

**Comment by Thulinma** [comment]
Fixed in current dev build - will make it into the 2.8 release.
