### ISSUE TITLE
Issue with overview

### ISSUE THREAD

**Issue by denellum** [DDVTECH/mistserver#16]
Looks like on 2.10 the overview page is now gone. I have tried upgrading, and then i tried a fresh install, overview page is just empty.
OS : centos 7, installed the linux 64bit

![overview](https://cloud.githubusercontent.com/assets/10350712/24107400/99a32c98-0d58-11e7-8a31-aab0075ffe8a.PNG)

**Comment by Thulinma** [comment]
Wow, that was fast! We're aware of the problem, and a patched release 2.10.1 will be going out later today.
Thanks for letting us know though, appreciate it!

**Comment by Thulinma** [comment]
Update: 2.10.1 is now online and fixes this issue.
