### ISSUE TITLE
Clean Build - Ubuntu 20.04

### ISSUE THREAD

**Issue by jjbarbosa7** [DDVTECH/mistserver#168]
Hello,

I'm new to the project (with very rusty C/C++ skills), and just attempted a clean build on Ubuntu 20.04. Aside from a couple minor issues (mbedcrypto not generating a pkg-config reference, missing meson project_source_root() method), I didn't seem to run into any issues with the meson build. But, when linking with ninja, I ran into the below. I'm not sure that I cloned/built the correct mbedtls and mbedcrypto libraries... any guidance would be appreciated.

ninja: Entering directory `build'
[73/568] Linking target subprojects/librist/librist.so.4.2.0.
FAILED: subprojects/librist/librist.so.4.2.0
c++  -o subprojects/librist/librist.so.4.2.0 'subprojects/librist/07978a0@@librist@sha/src_crypto_crypto.c.o' 'subprojects/librist/07978a0@@librist@sha/src_crypto_psk.c.o' 'subprojects/librist/07978a0@@librist@sha/src_flow.c.o' 'subprojects/librist/07978a0@@librist@sha/src_logging.c.o' 'subprojects/librist/07978a0@@librist@sha/src_rist.c.o' 'subprojects/librist/07978a0@@librist@sha/src_rist-common.c.o' 'subprojects/librist/07978a0@@librist@sha/src_rist_ref.c.o' 'subprojects/librist/07978a0@@librist@sha/src_rist-thread.c.o' 'subprojects/librist/07978a0@@librist@sha/src_mpegts.c.o' 'subprojects/librist/07978a0@@librist@sha/src_udp.c.o' 'subprojects/librist/07978a0@@librist@sha/src_stats.c.o' 'subprojects/librist/07978a0@@librist@sha/src_udpsocket.c.o' 'subprojects/librist/07978a0@@librist@sha/src_libevsocket.c.o' 'subprojects/librist/07978a0@@librist@sha/contrib_aes.c.o' 'subprojects/librist/07978a0@@librist@sha/contrib_sha256.c.o' 'subprojects/librist/07978a0@@librist@sha/contrib_fastpbkdf2.c.o' 'subprojects/librist/07978a0@@librist@sha/contrib_stdio-shim.c.o' 'subprojects/librist/07978a0@@librist@sha/contrib_time-shim.c.o' 'subprojects/librist/07978a0@@librist@sha/contrib_pthread-shim.c.o' 'subprojects/librist/07978a0@@librist@sha/contrib_linux-crypto.c.o' 'subprojects/librist/07978a0@@librist@sha/contrib_srp.c.o' 'subprojects/librist/07978a0@@librist@sha/src_eap.c.o' -Wl,--as-needed -Wl,--no-undefined -shared -fPIC -Wl,--start-group -Wl,-soname,librist.so.4 -pthread /usr/local/lib/libmbedcrypto.a /usr/local/lib/libcjson.so.1.7.15 -Wl,--end-group
/usr/bin/ld: subprojects/librist/07978a0@@librist@sha/src_crypto_psk.c.o: in function `_librist_crypto_aes_key':
/usr/local/src/mistserver/build/../subprojects/librist/src/crypto/psk.c:91: undefined reference to `mbedtls_pkcs5_pbkdf2_hmac'
/usr/bin/ld: /usr/local/lib/libmbedcrypto.a(md.c.o): relocation R_X86_64_PC32 against symbol `mbedtls_md5_info' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
[90/568] Compiling C++ object 'lib/76b5a35@@mist@sha/dtsc.cpp.o'.
ninja: build stopped: subcommand failed.

James

**Comment by jjbarbosa7** [comment]
Upgrading to a newer version (0.61.X) of meson resolved my issue; this version was able to automatically download and build the referenced subproject libraries.

**Comment by mist** [comment]
👀

**Comment by jjbarbosa7** [comment]
I know... should have checked that first after seeing the meson.project_source_root() error. Also should have started with a newer version of Ubuntu... would have avoided the issue entirely.

**Comment by Rokamun** [comment]
Hey James,

Meson should compile the libs you need automatically, but manual installs
would be used if compatible. So this "shouldn't" happen as far as I'm
aware. The first thing I would attempt is remove the manually installed
libraries, then recompile meson and see if it works.

Did you use any specific compile settings when setting up meson?

With kind regards,

Balder Viëtor
Head of Testing

**Comment by Rokamun** [comment]
And now seeing the issue in github I notice the mail compatibility doesn't give the full history. Seems you already found and solved this yourself, well done!

**Comment by Rokamun** [comment]
The Linux terminal comes to mind :)

In all seriousness we've made everything to not really be bound by a certain tool, so in theory you should be able to use whatever you prefer. Most of the core contributors are quite old-fashioned and stick to a terminal and a text-editor. Those that do use an IDE tend to use vscode.
