### ISSUE TITLE
Get list of streams

### ISSUE THREAD

**Issue by xtrasmal** [DDVTECH/mistserver#17]
Hi,

How do I get a list of streams, without all the configured streams being deleted?

**Comment by Thulinma** [comment]
As mentioned in section 4.1 of the [documentation](https://mistserver.org/guides/MistServer_Manual_2.13.pdf):
> For historical reasons, the “streams”, “config” and “log” API responses are always given, even
if not requested, unless the request “"minimal": 1” is sent along with the API requests.

So, just send an **empty** API request and read the "streams" object from the response.
