### ISSUE TITLE
Player.js doesn't work on Android

### ISSUE THREAD

**Issue by Shivang44** [DDVTECH/mistserver#20]
Hi,

First of all, thanks for such an amazing piece of open source software.

I'm using OBS to stream to the created stream in the MistServer web interface. I embedded the code it gave me with player.js.

It works great on desktop (tried chrome and edge) but on Android (chrome) it doesn't work well at all. Most of the time it will show a black screen, but sometimes it will play but just show a frame or two before freezing or buffering. What's interesting is I tried playing the .webm directly in the chrome Android browser and that doesn't play well either (it keeps buffering).

Any ideas why this isn't working well on mobile? I'm only streaming at around 1000 kbps, with keyframe interval 5 seconds, so I feel that it shouldn't be that hard to play on a mobile device.

**Comment by Shivang44** [comment]
I managed to find a fix, but I'm still not really sure why this fixes it. I did two things:

1. Disabled inspection in ngrok (I was using ingrok to create a tunnel to localhost) with inspect=false. This eliminated all buffering issues I had. 
2. To fix the video not working on mobile, I used video.js (and used the index.m3u8 url). It not works on both mobile and desktop. For some reason player.js insists on using the .webm version on chrome on android and, at least for me, this doesn't work.

Anyways, these are very specific issues/solutions so I chalk it up to my own environment (although the webm issue does seem to be related to player.js). Thanks again for this great software.

**Comment by Thulinma** [comment]
Thanks for the feedback!

We're about to release an update to our meta-player that greatly improves the featureset and compatibility.
Would you mind testing this on your device again after that update lands? That should be within the next 2-3 weeks. You can already try it out right now if you check out the "development" branch here on github, assuming you don't mind compiling the software yourself.
