### ISSUE TITLE
Livestreaming not working when pushing with wildcard

### ISSUE THREAD

**Issue by irg1008** [DDVTECH/mistserver#208]
Live streaming works when pushing to "normal" stream name, but won't work when pushing with wildcard

**Comment by irg1008** [comment]
This happens when using PUSH_REWRITE trigger and returning a stream name with wildcard. 

* Pushing from OBS with RTMP.

It's stuck in "Standby" but OBS does sent data

**Comment by irg1008** [comment]
It works when using PUSH_REWRITE and returning a stream name WITHOUT the wildcard but it doesn't with it. It's a big deal when you try to make dynamic streamings

**Comment by irg1008** [comment]
Basically:
```bash
$STREAM_NAME="live"

# Doesnt work
# echo "$STREAM_NAME+test"

# Works
echo "$STREAM_NAME
```

Calling this script with "blocking" on PUSH_REWRITE does or doesn't work as shown above

**Comment by Rokamun** [comment]
Hey there, 

That should actually work and it is quite a big part of our internal testing. So I would be surprised to find this broken without us noticing.

"Better" would be to use `echo -n` as that would remove the newline. Though we should filter that from the stream name, it could potentially cause issues if you have parameters set behind the `STREAM_NAME` part.

```
#!/bin/bash

STREAM_NAME="live"

# Doesnt work
# Edited: `echo -n` for removing newline. Also creating variable `STREAM_NAME` without `$` so the variable is created properly.
echo -n "$STREAM_NAME+test"

# Works
#echo "$STREAM_NAME"
```

I assume you're using a different method than this bash script though? Would it be possible to share that script/code? Feel free to mail it to our contact email ( info@mistserver.org ) directly if you don't want it shown on Github.

**Comment by irg1008** [comment]
OH MY GOD It works without the new line, (I am not experienced with shell scripts as you can see)

It works with my actual script as well. It's the one below:

```bash
#!/bin/bash

if [ -z "$MEDIA_SERVER_SECRET" ] ||
  [ -z "$MEDIA_SERVER_SIGNATURE_HEADER" ] ||
  [ -z "$MEDIA_SERVER_EVENT_URI" ] ||
  [ -z "$MEDIA_SERVER_TRIGGER_HEADER" ]; then
  echo "Missing required environment variables."
  exit 1
fi

# Get the trigger name (first argument)
TRIGGER_NAME="$1"

# Read from standard input (the payload)
PAYLOAD=""

while IFS= read -r LINE; do
  PAYLOAD+="$LINE"$'\n'
done

TIMESTAMP=$(date +%s%3N)

SIGNATURE=$(echo -n "$TIMESTAMP.$PAYLOAD" |
  openssl dgst -sha256 -hmac "$MEDIA_SERVER_SECRET" |
  awk '{print $2}')

AUTH_HEADER="t=$TIMESTAMP,v1=$SIGNATURE"

RESPONSE=$(curl -s -X POST \
  -H "content-type: text/plain" \
  -H "$MEDIA_SERVER_SIGNATURE_HEADER: $AUTH_HEADER" \
  -H "$MEDIA_SERVER_TRIGGER_HEADER: $TRIGGER_NAME" \
  -d "$PAYLOAD" \
  "$MEDIA_SERVER_EVENT_URI")

echo -n "$RESPONSE"
```

**Comment by irg1008** [comment]
You know this library it's actually great. One of those few that shows how much love and time has gone into it. Keep it up!!!

I will close this when you say sir, or you may, thanks again

**Comment by Rokamun** [comment]
No problem at all, it is actually quite a common issue we've had, I believe we do mention it into the documentation, but it's definitely not as easily findable as it should be. 
We do have plans for a basic "test my trigger" page/option within the interface that should also hint to things that might be wrong such as these. Sadly that's a bit off...

Still happy to have helped, feel free to close it whenever!
