### ISSUE TITLE
Backup / Restore

### ISSUE THREAD

**Issue by voltan** [DDVTECH/mistserver#22]
Hello

I start using Mistserver on my vod platform, and I have some question about usage ( at this moment I use open source version ), My first question is: how I can get backup from my data ( stream data ) and restore it

**Comment by Rokamun** [comment]
Hello Voltan, 

It depends on what you mean exactly. If you mean a backup of the server itself all configurations are saved in the MistServer configuration file (either the json.conf in the same folder as MistServer or available at /etc/mistserver.conf ).

If you mean a backup of your actual streams, MistServer doesn't do library management, it just uses what's given. So if you want to backup the streams you will have to do that manually or with another application.

I hope that answers your question, if not could you please word it differently?

**Comment by voltan** [comment]
Hello, Rokamun
thank you very much for your information, then the best way is take a full backup from VM, just can you please tell me, does mistserver usa any database to save stream information? I can get a backup from that database.

I will get backup from config files too

**Comment by Rokamun** [comment]
MistServer does not do any database handling unless you've included it through our Trigger system, which requires a MistServer Pro. So if you're looking to backup an Open Source MistServer from a VM the only thing you really need is the configuration file, it contains everything you've set up in MistServer as the Open Source version of MistServer just saves the location of the VoD files used in the configuration file.

MistServer does generate a small .dtsh file for every VoD file that's been included in MistServer (it will be placed next to the VoD file), but these are generated pretty quickly the first time a file gets used by MistServer so there's no need to pay them any mind. Though we have seen that it can take some time if your VoD files get larger than ~ 5GB. 

The .dtsh file includes header information to allow consistent use of more advanced media playback features over all protocols.

**Comment by voltan** [comment]
Thank you very much for your information. this information helps me to manage the service very well.

I published my video system as open-source and I support stream by mistserver to my system. this information helps me to improve my codes, I will write some api calls next week
