### ISSUE TITLE
v2.17 No "Public address" field for HTTP protocol

### ISSUE THREAD

**Issue by giachi** [DDVTECH/mistserver#26]
hello

I don't find "Public address" field for HTTP protocol for MistServer v2.17 for configure reverse proxy.

Can you help me ?
Thanck you.
Gérard

**Comment by Rokamun** [comment]
Hey Gérard,

The "Public address" feature is not available for HTTP in 2.17, just for HTTPS. We've added it to the HTTP protocol in our latest development version and we're hoping to release that soon. We're aiming for next week, but the COVID-19 lockdowns make proper timing a bit more challenging. 

I could see if I can send you a development build ahead of time if you really want the feature now however.

Regards,
Balder

**Comment by giachi** [comment]
Hi Balder

Thank you for your reply.
I also don't see for https?
I'm in no rush, but if you have a development version already ready, I'm ok.

Thanks again
Gérard

![Image 001](https://user-images.githubusercontent.com/16275750/78015307-89354d00-7349-11ea-9b19-b30eb1432ce9.png)

**Comment by Thulinma** [comment]
Just to clarify: this feature is currently in the dev branch for _both_ protocols, and will make it into the next release.

**Comment by giachi** [comment]
Hi
Thanks...
The image (above) is from the development version of this site.

**Comment by Thulinma** [comment]
Closing since this update released a few months ago. 😁

**Comment by giachi** [comment]
Yes, thancks, it work
