### ISSUE TITLE
fatal error: player.js.h: No such file or directory   862 | #include "player.js.h"

### ISSUE THREAD

**Issue by shashankmadhura** [DDVTECH/mistserver#41]
I am getting the above error while compiling. (AMD 64 bit machine)

**Comment by Thulinma** [comment]
Create a directory called `generated` in your compile directory and the problem should go away.
The cmakelists file is missing a command to create the directory if it's missing.

**Comment by shashankmadhura** [comment]
Thanks @Thulinma
