### ISSUE TITLE
sourcery usage in the (old) Makefile

### ISSUE THREAD

**Issue by jacand** [DDVTECH/mistserver#9]
In commit 9b6312c on April 2nd (switch to CMake), sourcery was changed from using stdout to taking an explicit output argument. The (old) Makefile, however, was not updated accordingly, so now a clean project build with good-old-Make fails due to an empty src/controller/server.html.h file (which should have been generated by sourcery).

In the same commit, the file embed.js.h was moved from src/ to src/output.

The fix is to remove the output redirect ">" from both sourcery invocations and substitute src/embed.js.h -> src/output/embed.js.h a few places in the Makefile ;-)

Also in the Makefile line 159 add src/io.cpp to the input list (this problem was introduced by commit d370ef4)

**Comment by Thulinma** [comment]
Thanks for looking into all this! The old Makefile was just kept there for backup purposes initially. We've since completely removed it as more and more things started breaking on it, and the cmake method is now the only way to compile. :-)
