### ISSUE TITLE
Pretty print config file on save

### ISSUE THREAD

**Issue by cyberj0g** [DDVTECH/mistserver#97]
I'm sure many people are editing `mistserver.conf` manually, and it gets one-lined on each server restart.

**Comment by AlexKordic** [comment]
So far i am using command to overwrite config before each mist start:
`cd build`
`cp ../../config.json ../startup.json; ./MistController --debug=8 -c ../startup.json`

**Comment by nerijus** [comment]
Agree, it would be nice to pretty print config file on save.
